build kubevirt-testing image for multi-arch
kubevirt/kubevirtci pull request #406
Opened 2020-07-10 09:23 UTC by zhlhahaha

Build kubevirt-testing image for multi-arch

2020-07-10 09:25 UTC, zhlhahaha commented
@davidvossel Can you review it when you have time?

2020-09-16 10:06 UTC, dhiller commented
/test all

2020-09-16 10:12 UTC, dhiller reviewed
/lgtm

Maybe we should add a presubmit job executing the build.sh? WDYT?

2020-09-16 10:16 UTC, dhiller approved these changes

2020-09-17 05:50 UTC, zhlhahaha commented
> /lgtm
> 
> Maybe we should add a presubmit job executing the build.sh? WDYT?

Yes, and I do not find any prow job for building and publishing kubevirt-testing image. I am confused about how kubevirt-testing publish in dockerhub.

2020-12-18 02:28 UTC, zhlhahaha commented
@phoracek Would you mind review this patch when you have time?

2020-12-21 07:59 UTC, rmohr commented
/uncc @phoracek

2020-12-21 08:00 UTC, rmohr commented
/cc @fgimenez 

@fgimenez I think we will discuss all this also on kubevirt-dev and on the mailing list, FYI right now.

2020-12-21 10:41 UTC, fgimenez requested changes
Looks good, we only need to push the images to quay.io instead of docker.io, changes suggested for doing so. We need this https://github.com/kubevirt/project-infra/pull/789 to land first so that the required credentials are in place.

2020-12-21 10:41 UTC, fgimenez commented on cluster-provision/images/kubevirt-testing/build.sh
> +        docker buildx build --load --platform linux/${ARCH}  -t kubevirtci/kubevirt-testing-${ARCH} --build-arg BASEIMAGE=${baseimage} ${SCRIPT_DIR}
```suggestion
        docker buildx build --load --platform linux/${ARCH}  -t quay.io/kubevirt/kubevirt-testing-${ARCH} --build-arg BASEIMAGE=${baseimage} ${SCRIPT_DIR}
```

2020-12-21 10:41 UTC, fgimenez commented on cluster-provision/images/kubevirt-testing/publish.sh
> +docker manifest push docker.io/${REPOSITORY}/kubevirt-testing:latest
```suggestion
DOCKER_PREFIX=quay.io
REPOSITORY="kubevirt"
ARCHS="amd64 arm64 ppc64le"

# set tags and push multiarch images
for ARCH in ${ARCHS}; do
        docker tag ${DOCKER_PREFIX}/${REPOSITORY}/kubevirt-testing-${ARCH} ${DOCKER_PREFIX}/${REPOSITORY}/kubevirt-testing-${ARCH}
        docker push ${DOCKER_PREFIX}/${REPOSITORY}/kubevirt-testing-${ARCH}
        manifest+=("${DOCKER_PREFIX}/${REPOSITORY}/kubevirt-testing-${ARCH}:latest")
done

# create and push manifest
docker manifest create --amend ${DOCKER_PREFIX}/${REPOSITORY}/kubevirt-testing:latest "${manifest[@]}"
set -x; for ${ARCH} in ${ARCHS}; do docker manifest annotate --arch ${ARCH} ${DOCKER_PREFIX}/${REPOSITORY}/kubevirt-testing:latest ${DOCKER_PREFIX}/${REPOSITORY}/kubevirt-testing-${ARCH}:latest; done
docker manifest push ${DOCKER_PREFIX}/${REPOSITORY}/kubevirt-testing:latest
```

2020-12-21 14:11 UTC, fgimenez approved these changes
/lgtm
/approve
/hold

Looks good thanks! Let's wait until https://github.com/kubevirt/project-infra/pull/789 lands to merge this one.

2021-01-15 10:13 UTC, rmohr commented
/close

With recent changes in kubevirt/kubevirt this PR is no longer needed to, since the test containers can be built for any kind of architecture now there. @zhlhahaha already incorporated these changes into this ppc64 PR in kubevirt/kubevirt.

2021-01-15 10:13 UTC, closed without merging